### ISSUE TITLE
Specflow3 + Visual Studio 2015 default XML namespace of the project must be the MSBuild xml namespace

### ISSUE THREAD

**Issue by AndresC46** [specsolutions/deveroom-visualstudio#30]
When I startup Visual Studio 2015 I get the following error:

The default XML namespace of the project must be the MSBuild xml namespace.  If the project is authored in the MsBuild 2003 format, please add
 xmlns='http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element.  If the project has been authored in the old 1.0 or 1.2, please convert to MSBuild 2003 format.
C:\<Project path>\packages\SpecFLow.Tools.MsBuild.Generation.3.0.199\build\SpecFlow.Tools.MsBuild.Generation.props.

Links to forum thread [https://groups.google.com/forum/#!topic/specflow/qCuKEROkY3Y](url)

**Comment by gasparnagy** [comment]
@AndresC46 I see. You have posted this message to a "Deveroom" topic in the forum, so I thought it is a Deveroom (a Visual Studio extension for SpecFlow) related issue. This is why I have suggested you to post it here. Generally, it makes sense to create new topics for new questions otherwise you will confuse people and you will not receive good answers. 

As it is stated in the SpecFlow documentation [here](https://specflow.org/documentation/Generate-Tests-from-MsBuild/), the SpecFlow.Tools.MsBuild.Generation package is only supported in VS2017 or above. If you need to use VS2015, you have to stick to SpecFlow v2.4, I think...

I close this issue here, if there are further comments on this, you need to re-open it in the SpecFlow project issues collection: https://github.com/techtalk/specflow/issues
