### ISSUE TITLE
Errors and warnings while building deveroom solution

### ISSUE THREAD

**Issue by kstudnik** [specsolutions/deveroom-visualstudio#53]
So it happened. My curiosity won, and I cloned deveroom project.
Using VS2019.
I updated missing required packages according to Contribution.md ( I was missing only the Visual Studio extension development package)
And at last, I tried to build the project. 
There were lots of warnings coming from the static analysis tool (about 160+). I assumed it comes from a different (maybe more strict) approach to coding in our local project, so I am not taking those into the topic.
But I wonder about only two errors. 
![image](https://user-images.githubusercontent.com/912304/66044780-9ac8a400-e522-11e9-84f5-7fcb0438eb2d.png)
```
MC1003	Project file cannot specify more than one ApplicationDefinition element.	Deveroom.VisualStudio.UI.Tester	C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets	243	

BG1003	The project file contains a property value that is not valid.	Deveroom.VisualStudio.UI.Tester	C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets	243	
```

When I am checking .csproj and .xaml properties, everything seems to be fine, but VS still throws them while rebuilding project `Deveroom.VisualStudio.UI.Tester`
I unloaded `Deveroom.VisualStudio.UI.Tester` temporarily, and solution builds fine 
Is it the case, that I have .NetCore 3.x present in my system?
Or I am missing something?

**Comment by gasparnagy** [comment]
Very good question. The UI tester project needed a bit of a hack, because the SDK-style project format that we use does not support natively WPF projects (in .NET Core 2.1 at least). 
I don't have NetCore 3 installed so this might be related, but it should not.

Please try these ideas maybe they help:

- Close VS and try to build the solution from MsBuild. If that works it might start working from VS too.
- Open `Directory.Build.targets` file from the UI tester project and remove the `**\` from the line with the ApplicationDefinition, so that it looks like this: `<ApplicationDefinition Include="App.xaml" />` 
- delete `Directory.Build.targets` file from the UI tester project entirely

The UI tester is a standalone executable to perform manual testing for the dialogs, you can live without it, so it is not a disaster if you can't get it compiled.

**Comment by gasparnagy** [comment]
I have temporarily removed the project from the solution...

**Comment by gasparnagy** [comment]
The UI tester project is enabled again...
